# Generated by Django 4.0.6 on 2022-07-20 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_alter_thought_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Thought',
        ),
    ]
