# Generated by Django 4.0.6 on 2022-07-23 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0013_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='Pic1.jpg', null=True, upload_to=''),
        ),
    ]
