# Generated by Django 4.0.6 on 2022-07-23 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0014_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
